# Generated by Django 5.2.6 on 2025-09-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='league',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('club_home', 'Club • Home'), ('club_away', 'Club • Away'), ('club_third', 'Club • Third'), ('club_gk', 'Club • Goalkeeper'), ('club_special', 'Club • Special/Anniv'), ('national_home', 'National • Home'), ('national_away', 'National • Away'), ('national_third', 'National • Third'), ('national_gk', 'National • Goalkeeper'), ('national_special', 'National • Special/Anniv'), ('retro', 'Retro/Classic'), ('limited', 'Limited Edition')], default='club_home', max_length=24),
        ),
    ]
