# Generated by Django 5.2.6 on 2025-09-15 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand_product_league_product_season_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='main_produc_slug_354b31_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
