# Generated by Django 5.2.6 on 2025-09-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand_product_league_product_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='main_produc_slug_354b31_idx'),
        ),
    ]
